version: '3.9'

services:

  postgres-fastapi:
    image: postgres:14.5
    expose:
      - 5432
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    depends_on:
      - postgres-fastapi
    volumes:
      - cache_data:/data

  file-server:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    ports:
      - 8080:8080
    env_file:
      - ./.env
    volumes:
      - media_data:/app/media/
    depends_on:
      - postgres-fastapi

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    restart:
      always
    depends_on:
      - file-server

volumes:
  postgres_data:
  cache_data:
  media_data: