version: '3.9'

services:

  postgres-fastapi:
    image: postgres:14.5
    ports:
      - "5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    depends_on:
      - postgres-fastapi
    volumes:
      - cache_data:/data

  file-server:
    build: .
    ports:
      - "8080"
    restart:
      always
    volumes:
      - media_data:/app/media/
    depends_on:
      - postgres-fastapi
      - cache
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./ngnix/nginx.conf:/etc/nginx/conf.d/default.conf
    restart:
      always
    depends_on:
      - file-server

volumes:
  postgres_data:
  cache_data:
  media_data: